name: my_assignment3
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
     sdk: flutter

  cupertino_icons: ^1.0.6
  connectivity_plus: 2.3.0
  get: ^4.6.5
  shared_preferences: ^2.0.8
  contacts_service: ^0.6.3
  permission_handler: ^10.2.0
  image_picker: ^0.8.4+5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/back1.jpeg
    - assets/lang/english.json
    - assets/lang/french.json
